export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_POSTAL = "CHANGE_POSTAL";
export const CHANGE_PASS = "CHANGE_PASS";
export const CHANGE_PASS_CONFIRMED = "CHANGE_PASS_CONFIRMED";
